gravitational/monitoring-app

resources/resources.yaml
Ensure we don't conflict with other ports by explicitly specifying all nodeports.
=> specify all node ports

resources/resources.yaml
As a result of securing kubelet communication on port `10250` - use default settings of using read-only-port (`10255`) over `HTTP` (related to https://github.com/gravitational/planet/pull/218)
=> heapster: use kubelet read-only-port for queries

images/Makefile, resources/resources.yaml
This is to mitigate issues with update when the older versions of the app (3.x) had the same kapacitor image tag but did not have credentials in the configuration.
Required for https://github.com/gravitational/gravity/issues/2460
=> Bump kapacitor tag

watcher/lib/grafana.go
Adding overwrite to change pre-existing dashboards, otherwise in case the Dashboard already exists you'll get a 412 (Conflict) error
=> Adding overwrite to change pre-existing dashboards

resources/resources.yaml
Required as part of removing hard-coded planet/1000 UID. When the cluster is configured with UID in range `2000-65535` (UID range predefined in `restricted` PSP) - for example with `20000`, the application resources might be validated against a `restricted` provider and then the containers with unspecified context will get a user assigned automatically from said range (will most likely run as UID `2000`) and containers will start failing with permission errors.
Updates https://github.com/gravitational/gravity/issues/3083.
=> Specify security context for kapacitor/influxdb/grafana containers explicitly

watcher/lib/constants/constants.go
Backporting FunctionCount to 4.x
=> Added Count function

watcher/lib/influxdb/rollups.go
Backported double quotes fix for rollup returned strings
=> Lele/fix rollups keywords escaping backport to 4.x

Makefile, images/buildbox.mk, images/hook/Dockerfile, watcher/Makefile
Update build box to build with go1.9.
Requires https://github.com/gravitational/rigging/pull/44
=> Update rigging to upcoming 0.0.10.

images/Makefile
Updated Grafana to 5.0.4
Tested locally, works with no further modifications.
=> Grafana to 5.0.4

resources/resources.yaml
Fixes collecting of metrics from heapster in k8s 1.9:
```
2018-05-01T00:34:00.148387Z log-forwarder-t5tzv telegraf-85468cc87d-j67dz_kube-system_telegraf-5c64cd728c0c64273986f6f058cacc4a412a5bed871705018ef190b43fdcd34e.log {"log":"2018-05-01T00:34:00Z E! Error in plugin [inputs.prometheus]: https://kubernetes.default.svc.cluster.local/metrics returned HTTP status 403 Forbidden\n","stream":"stderr","time":"2018-05-01T00:34:00.019852487Z"}
```
=> Fix issue with access rights to k8s metrics endpoint

resources/grafana-cfg.yaml
Explicitely set dashboards theme for clarity, also so that it can be
easily changed through automation (eg: with sed)
=> Explicitely set dashboards theme for clarity

watcher/lib/influxdb/rollups.go
Fixed templating type html->text to avoid double-escaping errors
=> Fixed templating type html->text

resources/telegraf.yaml
Telegraf DS splitted up into 2 DSs(master/worker) because on worker
nodes etcd is a Layer-4 gateway and it does not make sense to collect
any metrics from worker nodes.
=> Use nodeSelector for telegraf worker/master DS

resources/grafana.yaml, resources/nethealth/nethealth.yaml, resources/prometheus/0prometheus-operator-deployment.yaml, resources/prometheus/alertmanager-alertmanager.yaml, resources/prometheus/kube-state-metrics-deployment.yaml, resources/prometheus/node-exporter-daemonset.yaml, resources/prometheus/prometheus-adapter-deployment.yaml, resources/prometheus/prometheus-prometheus.yaml
In the latest Kubernetes, the label name changed from `beta.kubernetes.io/os` to `kubernetes.io/os` so half of monitoring app pods became unschedulable.
Instead of updating the label I just removed it, cause I don't see a lot of sense in having TBH. Let me know if you think it's better to update it instead.
=> Remove obsolete node selectors.

images/hook/entrypoint.sh, resources/install.sh, resources/nethealth/nethealth.yaml
Partial backport of #130.
* Add network health monitoring.
* Does not include added prometheus rules or changes to grafana
dashboard.
=> [5.5.x] Add nethealth monitoring

images/hook/entrypoint.sh, resources/nethealth/nethealth.yaml
- rigging fails to decode nethealth.yaml because of the included header.
May want to fix up rigging `Upsert` to handle this case. For now we are
removing the header from nethealth.yaml.
=> Remove header in nethealth.yaml

resources/nethealth/nethealth.yaml
- rigging fails to decode nethealth resource if header is included
=> Remove nethealth.yaml header

resources/nethealth/nethealth.yaml
Use nethealth 6.3.2 to fix sequence overflow bug.
=> [6.0.x] Fix sequence overflow bug

resources/rollups.yaml, watcher/Makefile, watcher/lib/influxdb/rollups.go
* Implement where clause for rollups definition.
Exclude sys_container type from memory and cpu continuous queries to
prevent memory leak when CronJobs are used.
Fixes https://github.com/gravitational/gravity/issues/1332.
=> Exclude sys_container type from CQ

resources/prometheus/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml, resources/prometheus/prometheus-adapter-configMap.yaml, resources/prometheus/prometheus-adapter-deployment.yaml, resources/prometheus/prometheus-rules.yaml
* This PR fixes:
- Issues with some graphs in Grafana.
- Issue with empty `kubectl top ` output.
- Issue with non-working HPA.
=> Fix rules for prometheus-adapter and prometheus in K8s 1.17+

resources/nethealth/nethealth.yaml
This PR bumps nethealth to 7.1.0.
- Nethealth now removes stale Prometheus metrics https://github.com/gravitational/satellite/pull/197.
- Nethealth image now uses distroless base image https://github.com/gravitational/satellite/pull/198.
=> Bump nethealth

resources/nethealth/nethealth.yaml
This PR bumps nethealth to 7.1.0.
- Nethealth now removes stale Prometheus metrics https://github.com/gravitational/satellite/pull/197.
- Nethealth image now uses distroless base image https://github.com/gravitational/satellite/pull/198.
=> [5.5.x] Bump nethealth

images/grafana/Dockerfile, images/hook/Dockerfile, images/hook/entrypoint.sh, images/mta/Dockerfile, resources/grafana.yaml, resources/install.sh, watcher/Dockerfile
All testing is done for 6.1.29+dev. Should work the same for 6.3.x.
=> [6.0.x] Backport changes from master

resources/grafana.yaml
Follow up for https://github.com/gravitational/monitoring-app/pull/163. Thanks to @stevenGravy he found more empty graphs. 
This patch applies only to Gravity 7.0. For 7.1+ I have another [PR](https://github.com/gravitational/monitoring-app/pull/162) with similar changes.
=> Fix grafana dashboards

images/Makefile, images/grafana/Dockerfile, images/grafana/rootfs/var/lib/grafana/dashboards/cluster.json, images/grafana/run.sh, resources/grafana.yaml
Fixes https://github.com/gravitational/gravity/issues/1703 in 5.5.x.
* Synchronized grafana dockerfile and run.sh with upstream.
* Updated UID for default dashboard to `default`, because URL `dashboard/db/cluster` is deprecated(see gravity [changes](https://github.com/gravitational/gravity/pull/1730/files#diff-f0cd04305a9ab5a61a359a9c56132b82L174)) and returns weird uid instead of using uid from dashboard definition.
* In this release grafana supports the substitution of ENV variables in provisioned resources, so no more `envsubst` in entrypoint. Changed yaml files accordingly.
=> Bump grafana version

watcher/lib/influxdb/influxdb.go, watcher/tool/watcher/dashboards.go, watcher/tool/watcher/main.go, watcher/tool/watcher/rollups.go
* Fix issue with out of bound error.
* Recreate rollup if it exist with the same name but different parameters.
=> Fix a few watcher issues with rollups

resources/nethealth/nethealth.yaml
This PR bumps nethealth to version 7.1.7. This updated nethealth version exposes an additional latency summary metric. This new metric will be used by the updated latency check.
* Requires https://github.com/gravitational/satellite/pull/277
=> Bump nethealth 7.1.7

resources/grafana.yaml, resources/nethealth/nethealth.yaml, resources/prometheus/0prometheus-operator-deployment.yaml, resources/prometheus/alertmanager-alertmanager.yaml, resources/prometheus/kube-state-metrics-deployment.yaml, resources/prometheus/node-exporter-daemonset.yaml, resources/prometheus/prometheus-adapter-deployment.yaml, resources/prometheus/prometheus-prometheus.yaml, resources/watcher.yaml
Customers can set any taint with an application manifest, so gravitational components sort of need to support any taint in order to run. This isn't a great solution, since we probably want to follow the builtin kubernetes health related taints. For now, support any taint so that customer applied taints don't block the builtins from functioning.
=> ensure gravitational services tolerate any taint

resources/grafana.yaml, resources/heapster.yaml, resources/influxdb.yaml, resources/kapacitor.yaml, resources/nethealth/nethealth.yaml, resources/telegraf.yaml
To support customers placing taints on their nodes, gravity services need to tolerate any taint.
Port #190 for InfluxDB monitoring stack.
Tracking: https://github.com/gravitational/gravity/issues/2281
=> monitoring-app services tolerate any taint

watcher/Makefile
This pr:
1) fixes ownership of the built `watcher` binary
2) opportunistically upgrades the go version
```
walt@work:~/git/monitoring-app$ make -C watcher                                                                    
make: Entering directory '/home/walt/git/monitoring-app/watcher'
mkdir -p /home/walt/git/monitoring-app/watcher/build
docker run -i --rm=true \
-u $(id -u):$(id -g) \
-v /home/walt/git/monitoring-app/watcher/:/gopath/src/github.com/gravitational/monitoring-app/watcher \
-e GOCACHE=/tmp/.cache \
quay.io/gravitational/debian-venti:go1.15.3-buster \
/bin/bash -c "make -C /gopath/src/github.com/gravitational/monitoring-app/watcher build-inside-container"
make: Entering directory '/gopath/src/github.com/gravitational/monitoring-app/watcher'
GOOS=linux GOARCH=amd64 go build …
```
=> Build watcher binary as non-root, upgrade go

images/hook/Dockerfile, resources/grafana.yaml, resources/nethealth/nethealth.yaml, resources/prometheus/0prometheus-operator-deployment.yaml, resources/prometheus/kube-state-metrics-deployment.yaml, resources/prometheus/node-exporter-daemonset.yaml, resources/prometheus/prometheus-adapter-deployment.yaml
This PR adds support for Kubernetes 1.19.
- Bump `rig` to `7.1.2`.
- `apps/v1beta2/{Deployment,DaemonSet}` is deprecated. Use `apps/v1/{Deployment,DaemonSet}` instead.
- `extensions/v1beta1/PodSecurityPolicy` is deprecated. Use `policy/v1beta1/PodSecurityPolicy` instead.
=> Kubernetes 1.19 support

images/hook/entrypoint.sh, resources/install.sh, resources/prometheus/node-exporter-daemonset.yaml, resources/prometheus/node-exporter-service.yaml
Fixes gathering mount points errors in logs in node-exporter container:
``` shell
time="2021-03-29T20:07:41Z" level=error msg="error gathering metrics: 14 error(s) occurred:\n* [from Gatherer #2] collected metric \"node_filesystem_device
_error\" { label:<name:\"device\" value:\"tmpfs\" > label:<name:\"fstype\" value:\"tmpfs\" > label:<name:\"mountpoint\" value:\"/run\" > gauge:<value:0 > }
was collected before with the same name and label values\n* [from Gatherer #2] collected metric \"node_filesystem_size_bytes\" { label:<name:\"device\" va
lue:\"tmpfs\" > label:<name:\"fstype\" value:\"tmpfs\" > label:<name:\"mountpoint\" value:\"/run\" > gauge:<value:3.124826112e+09 > } was collected before
with the same name and label values\n* [from Gatherer #2] collected metric …
```
=> [7.0.x] Update node exporter collector configuration

images/Dockerfile, images/buildbox.mk, images/heapster/Makefile, watcher/Makefile
Without this, the build creates some artifacts as root, while failing
when run as root for other artifacts.  Most notably this showed up
as part of the Drone CI build, which runs as root:
useradd --uid $BUILD_UID builder
useradd: UID 0 is not unique
As seen at https://drone.teleport.dev/gravitational/gravity/183/1/6
Backports 7bfff6f38d320ad02ce47292f8e2ad96eac881c1 / #201 
<details><summary>as non-root</summary>
```console
walt@work:~/git/monitoring-app$ make clean
make -C watcher clean
make[1]: Entering directory '/home/walt/git/monitoring-app/watcher'
rm -rf /home/walt/git/monitoring-app/watcher/build
make[1]: Leaving directory '/home/walt/git/monitoring-app/watcher'
make -C images clean
make[1]: Entering directory '/home/walt/git/monitoring-app/images'
make -C …
```
=> [5.5] Run build under current user

images/hook/Dockerfile
I realize this is a bump from 6.0 -> 6.1, but 6.1 is our LTS release but the monitoring-app was left on 6.0. So use rigging from the LTS release.
=> [6.0] bump rigging to 6.1.5

resources/charts/watcher/templates/role.yaml, resources/custom-values.yaml, watcher/lib/resources/resources.go
After migration to Helm charts the name of the services changed and that broke the alerts watcher.
+ skip tls verification for kube-scheduler and controller-manager.
=> Fix watcher pointing to the wrong services

resources/charts/kube-prometheus-stack/Chart.lock, resources/charts/kube-prometheus-stack/charts/grafana/Chart.yaml, resources/charts/kube-prometheus-stack/charts/grafana/templates/_helpers.tpl, resources/charts/kube-prometheus-stack/charts/kube-state-metrics/Chart.yaml, resources/charts/kube-prometheus-stack/charts/kube-state-metrics/values.yaml, resources/charts/kube-prometheus-stack/charts/prometheus-node-exporter/Chart.yaml, resources/charts/kube-prometheus-stack/charts/prometheus-node-exporter/templates/daemonset.yaml, resources/charts/kube-prometheus-stack/charts/prometheus-node-exporter/values.yaml
All dependency charts were updated to their patch version, which I assume is safe enough.
Mostly the bump happened just for the node-exporter chart to fix the issue above on AWS instances, but `help dep update` bumps everything automatically to patch versions and I decided to leave them updated.
```
level=error ts=2021-11-17T16:43:21.407Z caller=collector.go:169 msg="collector failed" name=nvme duration_seconds=2.7749e-05 err="error obtaining NVMe class info: failed to list NVMe devices at \"/host/sys/class/nvme\": open /host/sys/class/nvme: no such file or directory"
```
=> [AOP-3772] Bump dependency charts versions
