- resources/app.yaml
Bump resource version in manifest
> Relfect the change of the hook container to a debian-tall image

- Makefile
- images/Makefile
- images/influxdb/Makefile
- resources/app.yaml
- resources/resources.yaml
* Add import target
* Fix for https://github.com/gravitational/gravity/issues/574
> Better version control (like in pithos-app)

- images/buildbox.mk
- images/heapster/Makefile
Yeah, I now that `sudo`-everything code is ugly, but it's fast and working solution.
Fixes https://github.com/gravitational/gravity/issues/476
> Build as unprivileged user

- images/hook/entrypoint.sh
- resources/grafana-creds.yaml
- resources/install.sh
Closes gravitational/gravity#1449.
> Create secret/configmap during upgrade

- images/hook/entrypoint.sh
- resources/install.sh
> Generate grafana password without new line symbol (backport)

- resources/grafana-creds.yaml
- resources/install.sh
Encode password placeholder as base64 to comply with Secret data attribute format
> Adhere to Secret serilization schema

- images/Makefile
- images/buildbox.mk
- images/hook/entrypoint.sh
- images/influxdb/Makefile
- images/influxdb/config.toml
- resources/resources.yaml
- watcher/Makefile
- watcher/lib/influxdb.go
Closes https://github.com/gravitational/gravity/issues/2126.
> Upgrade InfluxDB to 1.2.2

- images/hook/entrypoint.sh
Create new resources if needed while upgrading.
> fix update

- images/kapacitor/kapacitor.conf
> only notify on state change

- README.md
Brief documentation about Kapacitor.
> docs about kapacitor

- Makefile
Fixes https://github.com/gravitational/gravity/issues/2273
> Only vendor relevant parts

- resources/resources.yaml
Make all labels consistent across deployments.
> cleanup labels

- resources/resources.yaml
> read only dashboards

- images/hook/entrypoint.sh
- resources/resources.yaml
Add security contexts where possible and make heapster talk to kubelet securely.
> Security improvements

- images/hook/entrypoint.sh
- images/influxdb/Dockerfile
- resources/resources.yaml
* Fix update script to use deployments for all services and add missing services.
* Change mount point for InfluxDB config from `/etc` to `/etc/influxdb`. I think this might be the reason for `MountVolume.SetUp failed for volume "kubernetes.io/configmap/a29ae791-6c09-11e7-b1e2-028f3bece152-influxdb-config" (spec.Name: "influxdb-config") pod "a29ae791-6c09-11e7-b1e2-028f3bece152" (UID: "a29ae791-6c09-11e7-b1e2-028f3bece152") with: remove /var/lib/kubelet/pods/a29ae791-6c09-11e7-b1e2-028f3bece152/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy`.
> Monitoring app fixes

- images/Makefile
- images/heapster/Makefile
- resources/resources.yaml
* Upgrade heapster to v1.4.1.
* Make it use proper k8s config b/c the one it used before had limited permissions (i.e. no access to namespaces).
> Upgrade & fix heapster

- images/kapacitor/kapacitor.conf
- resources/influxdb-conf.yaml
> Disable usage reports for InfluxDB and Kapacitor

- resources/alerts.yaml
WIP because I will add inodes check
> Add filesystem alerts

- images/Makefile
- images/kapacitor/entrypoint.sh
- images/kapacitor/loadalerts.sh
- images/telegraf/Dockerfile
- images/telegraf/rootfs/etc/telegraf/telegraf-node.conf
- images/telegraf/rootfs/usr/local/bin/run-node.sh
- resources/alerts.yaml
- resources/resources.yaml
I bumped telegraf version to avoid using sed to replace something inside telegraf.conf. New Telegraf can work normally with ENV variables.
> etcd alerts

- images/hook/Dockerfile
Bump rig to version that supports Custom Resource Definitions // kubernetes 1.8+
> bump rig in hook container

- resources/resources.yaml
Added one "monitoring" dedicated service account in the "kube-system"
namespace for the monitoring app.
Changed all resources to use the ServiceAccount.
> Changed entire monitoring-app to use dedicated SA

- Makefile
- images/Makefile
- images/buildbox.mk
- images/grafana/Dockerfile
- images/heapster/Makefile
- images/influxdb/Makefile
- images/kapacitor/Dockerfile
- images/telegraf/Dockerfile
- resources/resources.yaml
- watcher/Makefile
targets of Makefile in root directory are the same, should be fully backward-compatible
> Makefiles refactored

- watcher/lib/constants/constants.go
> Added count() function

- watcher/lib/constants/constants.go
- watcher/lib/influxdb/rollups.go
Adding missing Aggregate/Selector functions in InfluxDB CM parsing
> Adding missing Aggregate/Selector functions

- watcher/lib/influxdb/rollups.go
Added double-quotes to wrap potential keywords in rollups queries
> Added double-quotes to wrap potential keywords in rollups queries

- watcher/lib/constants/constants.go
- watcher/lib/influxdb/rollups.go
Fixed function logic and bugs presented by Roman in 
https://github.com/gravitational/monitoring-app/pull/73
> Fixed function logic and bugs

- watcher/lib/constants/constants.go
- watcher/lib/influxdb/rollups.go
Adding missing Aggregate/Selector functions in InfluxDB CM parsing, in branch 4.x
> Backporting newly added InfluxDB aggregated/selector functions to 4.x

- Makefile
- images/hook/Dockerfile
Required for upgrade to Kubernetes v1.9.
> Upgrade rig to 0.0.9.

- Makefile
Added --insecure and EXTRA_GRAVITY_OPTIONS to `export` as it is used on `import` as well
> Added --insecure and EXTRA_GRAVITY_OPTIONS to export

- images/Makefile
- images/grafana/Dockerfile
- images/grafana/run.sh
- images/hook/entrypoint.sh
- resources/grafana-cfg.yaml
- resources/grafana-ini.yaml
- resources/install.sh
- resources/resources.yaml
* Updated Grafana to latest 5.1.0
* Changed Grafana Configuration to be ConfigMap based
> Add support for ConfigMap based Grafana Configuration + Grafana Update

- Makefile
- images/Makefile
- images/grafana/Dockerfile
- images/grafana/run.sh
- images/hook/entrypoint.sh
- resources/grafana-cfg.yaml
- resources/grafana-ini.yaml
- resources/install.sh
- resources/resources.yaml
Backported latest Grafana changes to 5.0.x
> Backported latest Grafana changes to 5.0.x

- README.md
- images/hook/Dockerfile
- images/hook/entrypoint.sh
- images/telegraf/rootfs/etc/telegraf/telegraf-node.conf
- images/telegraf/rootfs/etc/telegraf/telegraf.conf
- resources/alerts.yaml
- resources/app.yaml
- resources/grafana.yaml
- resources/heapster.yaml
- resources/influxdb.yaml
- resources/install.sh
- resources/kapacitor.yaml
- resources/namespace.yaml
- resources/security.yaml
- resources/smtp.yaml
- resources/telegraf.yaml
- watcher/lib/constants/constants.go
- watcher/lib/kubernetes/kubernetes.go
- watcher/tool/watcher/alerts.go
+ Fixed RBAC issue with alers watcher
> Move monitoring stuff to another namespace

- images/telegraf/rootfs/etc/telegraf/telegraf-node.conf
Updates: https://github.com/gravitational/gravity.e/issues/3726
Use mTLS for polling satellite.
> monitor satellite using mTLS

- resources/grafana.yaml
Changed grafana theme to light
> Changed grafana theme to light

- images/telegraf/rootfs/etc/telegraf/telegraf-node.conf
- images/telegraf/rootfs/etc/telegraf/telegraf.conf
- resources/grafana.yaml
* Re-enabled system plugin
* Added Load average monitoring (1/5/15)
> Re-enabled system plugin, added load avg monitoring

- resources/grafana.yaml
> Fixed missing commas

- images/Makefile
- images/hook/entrypoint.sh
- images/telegraf/rootfs/etc/telegraf/telegraf-node-master.conf
- images/telegraf/rootfs/etc/telegraf/telegraf.conf
- resources/grafana.yaml
- resources/install.sh
- resources/rollups.yaml
> Update Cluster dashboard

- images/grafana/Dockerfile
- images/heapster/Dockerfile
- images/hook/Dockerfile
- images/influxdb/Dockerfile
- images/kapacitor/Dockerfile
- images/telegraf/Dockerfile
- watcher/Dockerfile
Add nsswitch.conf to each container, so the golang resolver will use the hosts file to determine localhost.
> fix localhost resolution

- images/grafana/Dockerfile
- images/hook/Dockerfile
- images/mta/Dockerfile
- watcher/Dockerfile
> Fix localhost resolution for golang processes

- resources/nethealth/nethealth.yaml
> Use nethealth 5.5.12

- images/hook/entrypoint.sh
- resources/nethealth/nethealth.yaml
- watcher/lib/influxdb/rollups.go
* Delete rig status from the start of upgrade hook.
* Fix check for influxdb pod.
* Delete unused fields/params from nethealth resources.
* Fix where clause for rollups creation template.
> Update hook revised

- images/hook/entrypoint.sh
Fixes https://github.com/gravitational/gravity/issues/1587
> Do not check status for the second invocation of upgrade

- images/hook/Dockerfile
- resources/grafana.yaml
- resources/heapster.yaml
- resources/influxdb.yaml
- resources/kapacitor.yaml
- resources/nethealth/nethealth.yaml
- resources/security.yaml
- resources/telegraf.yaml
Required for [gravity #1692](https://github.com/gravitational/gravity/pull/1692)
> [5.5.x] Add priority classes to resources

- images/Makefile
- images/grafana/Dockerfile
- images/grafana/rootfs/etc/grafana/dashboards/k8s-resources-workload.json
- images/grafana/rootfs/etc/grafana/dashboards/k8s-resources-workloads-namespace.json
- images/grafana/rootfs/etc/grafana/dashboards/k8s-resources.pod.json
- images/grafana/run.sh
- resources/grafana.yaml
* Forward-port of https://github.com/gravitational/monitoring-app/pull/176
* Fixed a few empty graphs
> [6.0.x ]Forward port grafana CVE fix

- resources/grafana.yaml
- resources/prometheus/0prometheus-operator-deployment.yaml
- resources/prometheus/alertmanager-alertmanager.yaml
- resources/prometheus/kube-state-metrics-deployment.yaml
- resources/prometheus/node-exporter-daemonset.yaml
- resources/prometheus/prometheus-adapter-deployment.yaml
- resources/prometheus/prometheus-prometheus.yaml
- resources/security.yaml
- resources/watcher.yaml
Forward-port of https://github.com/gravitational/monitoring-app/pull/175 to master.
> Set high priority class for resources

- resources/grafana.yaml
- resources/prometheus/0prometheus-operator-deployment.yaml
- resources/prometheus/alertmanager-alertmanager.yaml
- resources/prometheus/kube-state-metrics-deployment.yaml
- resources/prometheus/node-exporter-daemonset.yaml
- resources/prometheus/prometheus-adapter-deployment.yaml
- resources/prometheus/prometheus-prometheus.yaml
- resources/security.yaml
- resources/watcher.yaml
Forward-port of #175 to 7.0.x.
> [7.0.x] Set high priority class for resources

- images/hook/entrypoint.sh
Do not fail if drop series command exits with non-zero exit code, which makes
whole if block optional.
----
#
> Drop sys_container series during upgrade.

- resources/grafana.yaml
- resources/kube-prometheus-setup/prometheus-operator-deployment.yaml
- resources/nethealth/nethealth.yaml
- resources/prometheus/alertmanager-alertmanager.yaml
- resources/prometheus/kube-state-metrics-deployment.yaml
- resources/prometheus/node-exporter-daemonset.yaml
- resources/prometheus/prometheus-adapter-deployment.yaml
- resources/prometheus/prometheus-prometheus.yaml
- resources/watcher.yaml
(cherry picked from commit 83e696c573a061701529bdeded2a6bcf4adf5bf4)
> ensure gravitational services tolerate any taint (#190)

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
In anticipation of increased outside contribution, add our standard
contributing documentation.
Also remove some outdated information in the README. Further cleanup is likely needed.
@UnderGreen, any opinion on what can be purged?
Part of a series contributing to https://github.com/gravitational/gravity/pull/2429
> Add CONTRIBUTING and CODE_OF_CONDUCT

- images/hook/Dockerfile
Bump rig to 7.1.3. Pull in changes from https://github.com/gravitational/rigging/pull/100
> Bump rigging to 7.1.3

- images/kapacitor/Dockerfile
Make sure nsswitch get's created in resulting docker image in the multi-stage build.
> fix nsswitch in kapacitor code
